# Small experiment on event 40

In [14]:
import pandas as pd
import numpy as np
from energy_fault_detector import Config, FaultDetector
from energy_fault_detector.evaluation import Care2CompareDataset, CAREScore
from energy_fault_detector.utils.visualisation import plot_learning_curve, plot_score_with_threshold, plot_reconstruction

**Loading the data**

In [15]:
# Specify the path to the data
data_path = '../data/CARE_To_Compare'

c2c = Care2CompareDataset(path=data_path)

# event selection
event_id = 40
event_info = c2c.get_event_info(event_id=event_id)
event_info

asset_id                                    10
event_id                                    40
event_label                            anomaly
event_start                2022-12-26 00:00:00
event_start_id                           51363
event_end                  2023-01-26 13:00:00
event_end_id                             55870
event_description    Generator bearing failure
wind_farm                                    A
Name: 6, dtype: object

**Data is loaded, prepared and split into train and test data**

In [16]:
# load and split data into numerical sensor data and status_data
train_sensor_data, train_status, test_sensor_data, test_status = c2c.load_and_format_event_dataset(event_id=event_id, index_column='time_stamp')

train_sensor_data.shape, train_status.shape, test_sensor_data.shape, test_status.shape

((51219, 54), (51219,), (4939, 54), (4939,))

In [17]:
train_sensor_data.head()

,Ambient temperature (avg),Wind absolute direction (avg),Wind relative direction (avg),Windspeed (avg),Estimated windspeed (avg),Pitch angle (avg),Temperature in the hub controller (avg),Temperature in the top nacelle controller (avg),Temperature in the choke coils on the VCS-section (avg),Temperature on the VCP-board (avg),...,Active power - generator disconnected,Active power - generator connected in delta,Active power - generator connected in star,Reactive power - generator disconnected,Reactive power - generator connected in delta,Reactive power - generator connected in star,Total active power,Total reactive power,Rotor rpm (avg),Temperature in the nose cone (avg)
time_stamp,,,,,,,,,,,,,,,,,,,,,
2022-01-01 00:00:00,18.0,220.1,6.1,5.2,5.1,-1.3,27.0,38.0,93.0,39.0,...,0.0,33173.0,0.0,0.0,-13513.0,0.0,33173.0,-13513.0,11.2,19.0
2022-01-01 00:10:00,18.0,218.7,4.7,5.7,5.3,-1.6,27.0,38.0,93.0,39.0,...,0.0,38381.0,0.0,0.0,-15366.0,0.0,38381.0,-15366.0,11.7,19.0
2022-01-01 00:20:00,18.0,216.7,2.7,6.2,5.8,-1.9,27.0,38.0,93.0,39.0,...,0.0,52055.0,0.0,0.0,-15709.0,0.0,52055.0,-15709.0,12.0,19.0
2022-01-01 00:30:00,18.0,197.9,-16.1,6.3,6.2,-1.9,27.0,38.0,93.0,39.0,...,0.0,66365.0,0.0,0.0,-16444.0,0.0,66365.0,-16444.0,12.2,19.0
2022-01-01 00:40:00,18.0,217.2,3.2,6.6,6.1,-2.0,27.0,38.0,93.0,39.0,...,0.0,60980.0,0.0,0.0,-16344.0,0.0,60980.0,-16344.0,12.6,19.0

The status data contains a simple boolean value, indicating whether the status of the wind turbine was normal.

In [18]:
train_status.head()

time_stamp
2022-01-01 00:00:00    True
2022-01-01 00:10:00    True
2022-01-01 00:20:00    True
2022-01-01 00:30:00    True
2022-01-01 00:40:00    True
Name: status_type_id, dtype: bool

**Train the model**

In [20]:
# The EnergyFaultDetector needs a configuration - here we load a specific configuration for this dataset...
config = Config(config_filename='../configs/config.yaml')
# ...and update features to exclude (counters) and angles for data preprocessing
c2c.update_c2c_config(config=config, wind_farm='A')

model = FaultDetector(config=config, model_directory="../results")
train_results = model.fit(sensor_data=train_sensor_data, normal_index=train_status, save_models=True)

# save the model manually if needed by using
# model.save_models(model_name='my_model') or set save_models=True (default value)

2026-10-25 14:30:26,374 - energy_fault_detector - INFO - Initialize models..
2026-10-25 14:30:26,701 - energy_fault_detector - INFO - Fit preprocessor pipeline.
2026-10-25 14:30:27,254 - energy_fault_detector - INFO - Train autoencoder.
Epoch 1/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 0.2295 - mean_absolute_error: 0.3249 - val_loss: 0.0918 - val_mean_absolute_error: 0.2153
Epoch 2/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0680 - mean_absolute_error: 0.1850 - val_loss: 0.0531 - val_mean_absolute_error: 0.1644
Epoch 3/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0449 - mean_absolute_error: 0.1517 - val_loss: 0.0412 - val_mean_absolute_error: 0.1460
Epoch 4/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0358 - mean_absolute_error: 0.1358 - val_loss: 0.0336 - val_mean_absolute_error: 0.1320
Epoch 5/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0302 - mean_absolute_error: 0.1248 - val_loss: 0.0290 - val_mean_absolute_error: 0.1221
Epoch 6/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0264 - mean_absolute_error: 0.1162 - val_loss: 0.0282 - val_mean_absolute_error: 0.1201
Epoch 7/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0242 - mean_absolute_error: 0.1108 - val_loss: 0.0247 - val_mean_absolute_error: 0.1127
Epoch 8/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0223 - mean_absolute_error: 0.1065 - val_loss: 0.0234 - val_mean_absolute_error: 0.1095
Epoch 9/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0204 - mean_absolute_error: 0.1019 - val_loss: 0.0201 - val_mean_absolute_error: 0.1008
Epoch 10/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0188 - mean_absolute_error: 0.0982 - val_loss: 0.0185 - val_mean_absolute_error: 0.0972
Epoch 11/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0172 - mean_absolute_error: 0.0937 - val_loss: 0.0183 - val_mean_absolute_error: 0.0974
Epoch 12/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0159 - mean_absolute_error: 0.0904 - val_loss: 0.0161 - val_mean_absolute_error: 0.0906
Epoch 13/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0148 - mean_absolute_error: 0.0874 - val_loss: 0.0148 - val_mean_absolute_error: 0.0872
Epoch 14/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0139 - mean_absolute_error: 0.0846 - val_loss: 0.0140 - val_mean_absolute_error: 0.0849
Epoch 15/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0129 - mean_absolute_error: 0.0814 - val_loss: 0.0135 - val_mean_absolute_error: 0.0833
Epoch 16/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0122 - mean_absolute_error: 0.0794 - val_loss: 0.0123 - val_mean_absolute_error: 0.0795
Epoch 17/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0117 - mean_absolute_error: 0.0776 - val_loss: 0.0120 - val_mean_absolute_error: 0.0784
Epoch 18/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0108 - mean_absolute_error: 0.0745 - val_loss: 0.0108 - val_mean_absolute_error: 0.0743
Epoch 19/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0103 - mean_absolute_error: 0.0729 - val_loss: 0.0107 - val_mean_absolute_error: 0.0743
Epoch 20/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0098 - mean_absolute_error: 0.0713 - val_loss: 0.0104 - val_mean_absolute_error: 0.0725
Epoch 21/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0093 - mean_absolute_error: 0.0693 - val_loss: 0.0107 - val_mean_absolute_error: 0.0747
Epoch 22/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0089 - mean_absolute_error: 0.0680 - val_loss: 0.0104 - val_mean_absolute_error: 0.0738
Epoch 23/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0086 - mean_absolute_error: 0.0669 - val_loss: 0.0101 - val_mean_absolute_error: 0.0728
Epoch 24/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0082 - mean_absolute_error: 0.0651 - val_loss: 0.0087 - val_mean_absolute_error: 0.0673
Epoch 25/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0079 - mean_absolute_error: 0.0640 - val_loss: 0.0085 - val_mean_absolute_error: 0.0670
Epoch 26/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0076 - mean_absolute_error: 0.0629 - val_loss: 0.0079 - val_mean_absolute_error: 0.0641
Epoch 27/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0072 - mean_absolute_error: 0.0611 - val_loss: 0.0086 - val_mean_absolute_error: 0.0656
Epoch 28/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0069 - mean_absolute_error: 0.0601 - val_loss: 0.0072 - val_mean_absolute_error: 0.0612
Epoch 29/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0068 - mean_absolute_error: 0.0596 - val_loss: 0.0068 - val_mean_absolute_error: 0.0593
Epoch 30/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0064 - mean_absolute_error: 0.0581 - val_loss: 0.0071 - val_mean_absolute_error: 0.0612
Epoch 31/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0064 - mean_absolute_error: 0.0581 - val_loss: 0.0090 - val_mean_absolute_error: 0.0671
Epoch 32/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0062 - mean_absolute_error: 0.0570 - val_loss: 0.0066 - val_mean_absolute_error: 0.0582
Epoch 33/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0059 - mean_absolute_error: 0.0554 - val_loss: 0.0062 - val_mean_absolute_error: 0.0568
Epoch 34/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0058 - mean_absolute_error: 0.0550 - val_loss: 0.0060 - val_mean_absolute_error: 0.0559
Epoch 35/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0056 - mean_absolute_error: 0.0539 - val_loss: 0.0062 - val_mean_absolute_error: 0.0557
Epoch 36/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0054 - mean_absolute_error: 0.0533 - val_loss: 0.0056 - val_mean_absolute_error: 0.0536
Epoch 37/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0053 - mean_absolute_error: 0.0526 - val_loss: 0.0056 - val_mean_absolute_error: 0.0534
Epoch 38/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0052 - mean_absolute_error: 0.0520 - val_loss: 0.0053 - val_mean_absolute_error: 0.0523
Epoch 39/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0050 - mean_absolute_error: 0.0509 - val_loss: 0.0055 - val_mean_absolute_error: 0.0539
Epoch 40/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0049 - mean_absolute_error: 0.0504 - val_loss: 0.0057 - val_mean_absolute_error: 0.0544
Epoch 41/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0047 - mean_absolute_error: 0.0498 - val_loss: 0.0050 - val_mean_absolute_error: 0.0509
Epoch 42/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0046 - mean_absolute_error: 0.0491 - val_loss: 0.0049 - val_mean_absolute_error: 0.0507
Epoch 43/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0046 - mean_absolute_error: 0.0490 - val_loss: 0.0053 - val_mean_absolute_error: 0.0526
Epoch 44/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0044 - mean_absolute_error: 0.0479 - val_loss: 0.0046 - val_mean_absolute_error: 0.0489
Epoch 45/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0043 - mean_absolute_error: 0.0474 - val_loss: 0.0044 - val_mean_absolute_error: 0.0477
Epoch 46/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0041 - mean_absolute_error: 0.0464 - val_loss: 0.0045 - val_mean_absolute_error: 0.0482
Epoch 47/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0042 - mean_absolute_error: 0.0468 - val_loss: 0.0046 - val_mean_absolute_error: 0.0491
Epoch 48/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0040 - mean_absolute_error: 0.0454 - val_loss: 0.0043 - val_mean_absolute_error: 0.0475
Epoch 49/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0039 - mean_absolute_error: 0.0453 - val_loss: 0.0042 - val_mean_absolute_error: 0.0470
Epoch 50/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0038 - mean_absolute_error: 0.0444 - val_loss: 0.0043 - val_mean_absolute_error: 0.0475
Epoch 51/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0037 - mean_absolute_error: 0.0441 - val_loss: 0.0041 - val_mean_absolute_error: 0.0460
Epoch 52/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0036 - mean_absolute_error: 0.0435 - val_loss: 0.0038 - val_mean_absolute_error: 0.0446
Epoch 53/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0035 - mean_absolute_error: 0.0430 - val_loss: 0.0039 - val_mean_absolute_error: 0.0447
Epoch 54/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0035 - mean_absolute_error: 0.0428 - val_loss: 0.0036 - val_mean_absolute_error: 0.0431
Epoch 55/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0034 - mean_absolute_error: 0.0420 - val_loss: 0.0035 - val_mean_absolute_error: 0.0428
Epoch 56/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0033 - mean_absolute_error: 0.0417 - val_loss: 0.0034 - val_mean_absolute_error: 0.0421
Epoch 57/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0033 - mean_absolute_error: 0.0411 - val_loss: 0.0034 - val_mean_absolute_error: 0.0426
Epoch 58/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0032 - mean_absolute_error: 0.0407 - val_loss: 0.0033 - val_mean_absolute_error: 0.0412
Epoch 59/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0032 - mean_absolute_error: 0.0406 - val_loss: 0.0032 - val_mean_absolute_error: 0.0401
Epoch 60/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0031 - mean_absolute_error: 0.0399 - val_loss: 0.0036 - val_mean_absolute_error: 0.0443
Epoch 61/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0031 - mean_absolute_error: 0.0404 - val_loss: 0.0032 - val_mean_absolute_error: 0.0407
Epoch 62/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0029 - mean_absolute_error: 0.0389 - val_loss: 0.0032 - val_mean_absolute_error: 0.0403
Epoch 63/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0029 - mean_absolute_error: 0.0388 - val_loss: 0.0033 - val_mean_absolute_error: 0.0415
Epoch 64/1000
270/270 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0029 - mean_absolute_error: 0.0386 - val_loss: 0.0031 - val_mean_absolute_error: 0.0401
1077/1077 ━━━━━━━━━━━━━━━━━━━━ 1s 530us/step
270/270 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step
1601/1601 ━━━━━━━━━━━━━━━━━━━━ 1s 469us/step
2026-10-25 14:31:31,378 - energy_fault_detector - INFO - Fit threshold.
2026-10-25 14:31:31,416 - energy_fault_detector - INFO - Best F_0.5 score: 0.229, threshold: 1.12

In [21]:
train_results.model_date, train_results.model_path

('20261025_143131',
 '/cluster/home/selmaka/SCADA_model_testing/results/20261025_143131')

The FaultDetector.predict method returns a FaultDetectionResult object containing several result dataframes. <br>

**recon_error**: reconstruction error of the autoencoder<br>
**reconstruction**: reconstruction of the input data (rescaled to original scale)<br>
**predicted_anomalies**: series indicating whether an anomaly is detected<br>
**anomaly_score**: dataframe with column containing the Anomaly Score<br>
**bias_data**: dataframe with ARCANA bias vector, if root cause analysis was performed<br>
**arcana_losses**: dataframe containing recorded ARCANA losses<br>
**tracked_bias**: List of recorded biases during ARCANA iterations<br>

In [24]:
predictions = model.predict(sensor_data=test_sensor_data)

scores = pd.DataFrame({
    "event_id": event_id,
    "time_stamp": predictions.anomaly_score.index,
    "anomaly_score": predictions.anomaly_score.values,
    "predicted_anomaly": predictions.predicted_anomalies.values,
})
scores.to_csv(f"{train_results.model_path}/scores.csv")
scores.head()

155/155 ━━━━━━━━━━━━━━━━━━━━ 0s 622us/step

   event_id          time_stamp  anomaly_score  predicted_anomaly
0        40 2022-12-25 00:00:00       0.831964              False
1        40 2022-12-25 00:10:00       0.672310              False
2        40 2022-12-25 00:20:00       0.710605              False
3        40 2022-12-25 00:30:00       0.961502              False
4        40 2022-12-25 00:40:00       0.779310              False

### Plot the evaluation results

In [ ]:
fig, ax = plot_learning_curve(model)

In [ ]:
fig, ax = plot_score_with_threshold(model=model, data=test_sensor_data, normal_index=test_status)
ax.set_yscale('log')

In [ ]:
# Add the anomaly event
fig, ax = plot_score_with_threshold(model=model, data=test_sensor_data, normal_index=test_status)
ax.set_yscale('log')
ax.axvspan(event_info['event_start'], event_info['event_end'], alpha=0.1, color='red', label='anomaly event')
ax.legend(loc='upper left')

In [ ]:
# Add criticality information
fig, ax = plot_score_with_threshold(model=model, data=test_sensor_data, normal_index=test_status, show_criticality=True, figsize=(15, 6))
ax.set_yscale('log')
ax.axvspan(event_info['event_start'], event_info['event_end'], alpha=0.1, color='red', label='anomaly event')
ax.legend(loc='upper left')

In [ ]:
# Plot reconstruction of the first couple of features
fig, ax = plot_reconstruction(test_sensor_data, predictions.reconstruction, features_to_plot=predictions.reconstruction.columns[:20])

In [ ]:
# Plot the feature with the anomalous behaviour
fig, ax = plot_reconstruction(test_sensor_data, predictions.reconstruction, features_to_plot=['Temperature in the split ring chamber (avg)'])

### Evaluate results

In [12]:
from sklearn.metrics import fbeta_score, confusion_matrix, ConfusionMatrixDisplay

In [ ]:
# create boolean series with the ground truth for this dataset
ground_truth = CAREScore.create_ground_truth(
    event_start=event_info['event_start'],
    event_end=event_info['event_end'],
    event_label=event_info['event_label'],
    normal_index=test_status
)

predicted_anomalies = predictions.predicted_anomalies

fbeta_score(y_true=ground_truth, y_pred=predicted_anomalies, beta=1)

In [ ]:
disp = ConfusionMatrixDisplay(confusion_matrix(ground_truth, predicted_anomalies, labels=[False, True]),
                              display_labels=["Normal", "Anomaly"],)
disp.plot()